filebeat.inputs:
- type: filestream
  enabled: true
  paths: ["/home/data/fake-ecs/fake-ecs.txt"]
  enabled: true
  fields:
    log_type: fake-ecs

output.kafka:
  hosts: ["192.168.1.100:9092"]
  topic: "quickstart-events"
  version: "2.0.0"
  required_acks: 1
