filebeat.inputs:
- type: filestream
  id: fake-ecs
  enabled: true
  paths: ["/home/data/fake-ecs/fake-ecs.txt"]
  enabled: true
  fields:
    log_type: fake-ecs

output.kafka:
  hosts: ["kafka:9092"]
  topic: "quickstart-events"

logging.level: debug