version: '2'

networks:
  kafka:
    driver: bridge

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    networks:
      - kafka
  kafka:
    image: 'bitnami/kafka:latest'
    networks:
      - kafka
