version: '2'

services:
  logstash:
    image: docker.elastic.co/logstash/logstash:8.7.0
    container_name: logstash
    volumes:
      - ./pipeline:/usr/share/logstash/pipeline
      - ./logstash.yml:/usr/share/logstash/config/logstash.yml
    ports:
      - "5000:5000"
    depends_on:
      - elasticsearch
    networks:
      - elk-net
      - filebeat-kafka

  elasticsearch:
    build:
      context: .
      dockerfile: ./Dockerfile.elasticsearch
    container_name: elasticsearch
    ports:
      - "9200:9200"
    networks:
      - elk-net
  kibana:
    image: docker.elastic.co/kibana/kibana:8.7.0
    container_name: kibana
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elk-net

networks:
  elk-net:
    name: elk-net
    driver: bridge
  filebeat-kafka:
    name: filebeat-kafka
    external: true
