version: '2'

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:latest
    ports:
      - "2181:2181"
      - "8080:8080"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: docker.io/bitnami/kafka:latest
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true

    depends_on:
      - zookeeper

  akhq:
    image: tchiotludo/akhq
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "kafka:9092"
    ports:
      - 8082:8080
    links:
      - kafka
  # filebeat:
  #   image: docker.elastic.co/beats/filebeat:7.16.2
  #   user: root
  #   volumes:
  #     - "/home/data/fake-ecs:/home/data/fake-ecs:ro"
  #     - "./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro"
  #   command: [ "filebeat", "-e" ]
  #   depends_on:
  #     - kafka

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
