filebeat.inputs:
- type: log
  paths:
    - /home/data/fake-ecs/fake-ecs.txt
  fields:
    log_type: fake-ecs
  fields_under_root: true

output.kafka:
  hosts: ["localhost:9092"]
  topic: "fake_ecs_logs"
